services:
  db:
    image: postgres:latest
    container_name: album-dev
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'postgres'
volumes:
  db-store: